server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/houtai?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.tang.dao
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
